export const getPlaylistDetails = (id) => {
  const playlists = {
    1: {
      id: 1,
      title: "Assassin's Creed Valhalla - Walkthrough (PC)",
      channelName: "theNettko",
      videoCount: 6,
      views: 9,
      lastUpdated: "23 de dezembro",
      coverImage: "assassins-creed-valhalla.jpg",
      videos: [
        {
          id: 1,
          title: "Parte 1 Gameplay",
          duration: "30:10",
          views: 21,
          uploaded: "há 1 ano",
          thumbnail: "video1.jpg",
        },
        {
          id: 2,
          title: "Parte 2 Gameplay",
          duration: "17:32",
          views: 13,
          uploaded: "há 1 ano",
          thumbnail: "video2.jpg",
        },
      ],
    },
    2: {
      id: 2,
      title: "Cyberpunk 2077 Walkthrough",
      channelName: "GameMaster",
      videoCount: 8,
      views: 500,
      lastUpdated: "1 de agosto",
      coverImage: "cyberpunk2077.jpg",
      videos: [
        {
          id: 1,
          title: "Parte 1 - Intro",
          duration: "40:12",
          views: 200,
          uploaded: "há 6 meses",
          thumbnail: "cyberpunk1.jpg",
        },
        {
          id: 2,
          title: "Parte 2 - First Missions",
          duration: "45:30",
          views: 150,
          uploaded: "há 6 meses",
          thumbnail: "cyberpunk2.jpg",
        },
      ],
    },
    3: {
      id: 3,
      title: "The Witcher 3 - Complete Gameplay",
      channelName: "WitcherFan",
      videoCount: 12,
      views: 1200,
      lastUpdated: "15 de junho",
      coverImage: "witcher3.jpg",
      videos: [
        {
          id: 1,
          title: "Parte 1 - Geralt's Journey",
          duration: "50:20",
          views: 600,
          uploaded: "há 1 ano",
          thumbnail: "witcher1.jpg",
        },
        {
          id: 2,
          title: "Parte 2 - The Hunt",
          duration: "35:45",
          views: 400,
          uploaded: "há 1 ano",
          thumbnail: "witcher2.jpg",
        },
      ],
    },
    4: {
      id: 4,
      title: "Red Dead Redemption 2 - Full Playthrough",
      channelName: "CowboyGamer",
      videoCount: 10,
      views: 800,
      lastUpdated: "10 de julho",
      coverImage: "rdr2.jpg",
      videos: [
        {
          id: 1,
          title: "Parte 1 - The West",
          duration: "1:05:10",
          views: 400,
          uploaded: "há 8 meses",
          thumbnail: "rdr1.jpg",
        },
        {
          id: 2,
          title: "Parte 2 - The Gang",
          duration: "1:10:45",
          views: 300,
          uploaded: "há 8 meses",
          thumbnail: "rdr2.jpg",
        },
      ],
    },
    5: {
      id: 5,
      title: "Horizon Zero Dawn - Walkthrough",
      channelName: "FutureHunter",
      videoCount: 15,
      views: 900,
      lastUpdated: "5 de abril",
      coverImage: "horizon-zero-dawn.jpg",
      videos: [
        {
          id: 1,
          title: "Parte 1 - Aloy's Beginning",
          duration: "25:32",
          views: 500,
          uploaded: "há 1 ano",
          thumbnail: "horizon1.jpg",
        },
        {
          id: 2,
          title: "Parte 2 - First Hunt",
          duration: "35:20",
          views: 300,
          uploaded: "há 1 ano",
          thumbnail: "horizon2.jpg",
        },
      ],
    },
    6: {
      id: 6,
      title: "The Last of Us Part II",
      channelName: "SurvivalGamer",
      videoCount: 7,
      views: 1100,
      lastUpdated: "30 de setembro",
      coverImage: "last-of-us-2.jpg",
      videos: [
        {
          id: 1,
          title: "Parte 1 - The Journey Begins",
          duration: "1:15:42",
          views: 700,
          uploaded: "há 4 meses",
          thumbnail: "lastofus1.jpg",
        },
        {
          id: 2,
          title: "Parte 2 - Survival",
          duration: "50:30",
          views: 300,
          uploaded: "há 4 meses",
          thumbnail: "lastofus2.jpg",
        },
      ],
    },
    7: {
      id: 7,
      title: "God of War (2018) Playthrough",
      channelName: "SpartanGamer",
      videoCount: 12,
      views: 1300,
      lastUpdated: "2 de janeiro",
      coverImage: "god-of-war.jpg",
      videos: [
        {
          id: 1,
          title: "Parte 1 - Kratos' New Life",
          duration: "35:00",
          views: 800,
          uploaded: "há 2 anos",
          thumbnail: "gow1.jpg",
        },
        {
          id: 2,
          title: "Parte 2 - Into the Wild",
          duration: "40:12",
          views: 400,
          uploaded: "há 2 anos",
          thumbnail: "gow2.jpg",
        },
      ],
    },
    8: {
      id: 8,
      title: "Marvel's Spider-Man PS4",
      channelName: "WebSlinger",
      videoCount: 9,
      views: 900,
      lastUpdated: "10 de novembro",
      coverImage: "spiderman.jpg",
      videos: [
        {
          id: 1,
          title: "Parte 1 - Friendly Neighborhood",
          duration: "45:30",
          views: 500,
          uploaded: "há 1 ano",
          thumbnail: "spiderman1.jpg",
        },
        {
          id: 2,
          title: "Parte 2 - Villains",
          duration: "55:12",
          views: 400,
          uploaded: "há 1 ano",
          thumbnail: "spiderman2.jpg",
        },
      ],
    },
    9: {
      id: 9,
      title: "Ghost of Tsushima",
      channelName: "SamuraiSpirit",
      videoCount: 8,
      views: 1100,
      lastUpdated: "12 de fevereiro",
      coverImage: "ghost-of-tsushima.jpg",
      videos: [
        {
          id: 1,
          title: "Parte 1 - Jin's Path",
          duration: "30:20",
          views: 700,
          uploaded: "há 10 meses",
          thumbnail: "ghost1.jpg",
        },
        {
          id: 2,
          title: "Parte 2 - The First Battle",
          duration: "45:10",
          views: 400,
          uploaded: "há 10 meses",
          thumbnail: "ghost2.jpg",
        },
      ],
    },
    10: {
      id: 10,
      title: "Resident Evil Village Walkthrough",
      channelName: "SurvivorGamer",
      videoCount: 6,
      views: 1000,
      lastUpdated: "28 de março",
      coverImage: "resident-evil-village.jpg",
      videos: [
        {
          id: 1,
          title: "Parte 1 - Ethan's Return",
          duration: "50:20",
          views: 600,
          uploaded: "há 7 meses",
          thumbnail: "re-village1.jpg",
        },
        {
          id: 2,
          title: "Parte 2 - The Village",
          duration: "45:00",
          views: 400,
          uploaded: "há 7 meses",
          thumbnail: "re-village2.jpg",
        },
      ],
    },
  };

  return playlists[id] || null;
};
